### ISSUE TITLE
NSML Session 실행시 에러 질문입니다. 

### ISSUE THREAD

**Issue by Hyunjulie** [naver/nlp-challenge#13]
안녕하세요, 
`$ nsml run -e main.py -d NER` 

베이스라인 코드를 실행하는 과정에서 오류가 나서 질문드립니다. 
로컬 환경에서 코드를 돌리면 잘 돌아가는데, NSML 에 익숙하지 않아서 그런지 어느 부분에서 오류가 나는지 잘 모르겠습니다. 혹시 참고할만한 자료가 있다면 여쭤봐도 될까요? 

$ nsml run -e main.py -d NER
INFO[2018/11/22 02:12:43.247] file integrity check - start                 
... 
INFO[2018/11/22 02:13:24.753] setup.py 247 B - done (9/9 100.00%) (39 MiB/39 MiB 100.00%) 
Traceback (most recent call last):
  File "/app/src/main.py", line 5, in <module>
    nsml.nsml(obj={}, prog_name='nsml')
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/src/nsml_cli/nsml.py", line 584, in run
    gpu_driver_version, num_nodes
  File "/app/src/nsml_cli/sessions/session_service.py", line 837, in run_session
    _ = make_and_get_personal_minio(ctx.obj, user_id=owner)
  File "/app/src/nsml_cli/client/minio_client.py", line 450, in make_and_get_personal_minio
    server, passwd = _launch_minio(ctx_obj, user_id, redis_client)
  File "/app/src/nsml_cli/client/minio_client.py", line 418, in _launch_minio
    '--config-dir', '/etc/minio', 'server', '/data', encrypted=ctx_obj
  File "/app/src/nsml_cli/cluster.py", line 93, in docker
    return docker(self.address, *args, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 90, in docker
    return _run_docker_cmd(args, interactive, err, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 76, in _run_docker_cmd
    out = check_output(cmd, stderr=-2 if err else devnull)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', '--config', '/tmp/GimmeFive', '-H', '10.33.29.201', 'run', '--restart=always', '-d', '-p', '10132:9000', '--name=minio_GimmeFive', '-v', '/data/minio_client/GimmeFive:/data', '-e', 'MINIO_ACCESS_KEY=GimmeFive@github.com', '-e', 'MINIO_SECRET_KEY=ed74f266', 'minio/minio', '--config-dir', '/etc/minio', 'server', '/data']' returned non-zero exit status 125.

**Comment by Hyunjulie** [comment]
nsml-hack-examples/01.Basic/01_hello_nsml 에 있는 예제 코드를 실행시켜도 같은 에러가 납니다. 

FATA[2018/11/22 09:55:39.793] Internal server error                        

라고 나오는데, 이럴 때 참고할 만한게 있을까요?

**Comment by rkdls** [comment]
안녕하세요

서버에 문제가 있어서 현재는 수정 되었습니다. 다시한번 확인해보실래요?

감사합니다.

**Comment by Hyunjulie** [comment]
이제 잘 작동됩니다! 감사합니다 :D
