### ISSUE TITLE
baseline 실행 오류에 관해..

### ISSUE THREAD

**Issue by poble1** [naver/nlp-challenge#42]
Traceback (most recent call last):
  File "/app/src/main.py", line 5, in <module>
    nsml.nsml(obj={}, prog_name='nsml')
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/src/nsml_cli/nsml.py", line 584, in run
    gpu_driver_version, num_nodes
  File "/app/src/nsml_cli/sessions/session_service.py", line 837, in run_session
    _ = make_and_get_personal_minio(ctx.obj, user_id=owner)
  File "/app/src/nsml_cli/client/minio_client.py", line 450, in make_and_get_personal_minio
    server, passwd = _launch_minio(ctx_obj, user_id, redis_client)
  File "/app/src/nsml_cli/client/minio_client.py", line 418, in _launch_minio
    '--config-dir', '/etc/minio', 'server', '/data', encrypted=ctx_obj
  File "/app/src/nsml_cli/cluster.py", line 93, in docker
    return docker(self.address, *args, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 90, in docker
    return _run_docker_cmd(args, interactive, err, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 76, in _run_docker_cmd
    out = check_output(cmd, stderr=-2 if err else devnull)
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', '--config', '/tmp/naverEnding', '-H', '10.33.29.201', 'run', '--restart=always', '-d', '-p', '10209:9000', '--name=minio_naverEnding', '-v', '/data/minio_client/naverEnding:/data', '-e', 'MINIO_ACCESS_KEY=naverEnding@github.com', '-e', 'MINIO_SECRET_KEY=7522073f24454f8de4167b7e2f6c0323178ed199', 'minio/minio', '--config-dir', '/etc/minio', 'server', '/data']' returned non-zero exit status 125.
FATA[2018/12/05 21:19:41.274] Internal server error

다음과 같은 오류가 나는데 이건 nsml내부 서버 에러인가요?

또한 local 환경에서 실행하려 하는데, local 환경에서 실행하면 다음과 같은 오류가 납니다.
  File "main.py", line 7, in <module>
    import nsml
ImportError: No module named 'nsml'
nsml-local 프로그램도 설치 하였고, 재설치를 반복 했는데도 오류가 나는데 해결 방안이 있나요??

**Comment by nsml-admin** [comment]
안녕하세요

위와같은 에러는 현재 수정되었습니다. 다시한번 시도해주시면 해결될거라 추측됩니다.

또한 local환경에서의 ImportError는 실행되었을때의 python과 (nsml 을 제대로 설치하였다면)설치한 python의 라이브러리의 path가 달라서 nsml 패키지를 못찾는걸로 보여집니다.

감사합니다.
