### ISSUE TITLE
training 중단에러 

### ISSUE THREAD

**Issue by seanie12** [naver/nlp-challenge#48]
학습 도중 중간에 다음과 같은 메세지가 나오면서 종료되었습니다

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.5/dist-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2408, in _execute
    return command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/app/nsml/client.py", line 63, in run
    for item in self.pubsub.listen():
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2501, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2430, in parse_response
    return self._execute(connection, connection.read_response)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2415, in _execute
    connection.connect()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to 10.34.34.173:32770. Connection timed out.

**Comment by nsml-admin** [comment]
https://github.com/naver/nlp-challenge/issues/45
위 에러와 유사해보입니다.

불편을 드려서 죄송합니다.적정량의 크레딧을 추가해드렸습니다

감사합니다.
